### ISSUE TITLE
prpr-doc link is not working

### ISSUE THREAD

**Issue by liquidhelium** [Mivik/prpr#17]
![image](https://user-images.githubusercontent.com/59129152/230717323-b28ad3cb-1337-4dee-bbba-7a20c7d60d86.png)
如图

**Comment by Mivik** [comment]
Fixed

**Comment by liquidhelium** [comment]
从readme点进去依然有问题 需要加一个斜杠
![image](https://user-images.githubusercontent.com/59129152/230717951-f5be20c5-ec5b-4bb8-8d13-e41cb8a304fa.png)

**Comment by liquidhelium** [comment]
@Mivik

**Comment by Mivik** [comment]
> @Mivik

Should be ok know.
