### ISSUE TITLE
Error code 01

### ISSUE THREAD

**Issue by MTOtaku** [Mivik/prpr#18]
![IMG-20230420-WA0000](https://user-images.githubusercontent.com/131354909/233335730-995bb5d7-c492-47c3-bba6-091cf2ed6a17.jpeg)

Basically can't download a song from online tab or even can't log in on the account

**Comment by Mivik** [comment]
prpr's server is no longer available and it's suggested that users migrate to [Phira](https://github.com/TeamFlos/phira/releases)
