### ISSUE TITLE
Key Size Error

### ISSUE THREAD

**Issue by happymimimix** [Mivik/prpr#7]
Smaller keys seemed to be closer to the center than bigger keys.

**Comment by Mivik** [comment]
Fixed

**Comment by happymimimix** [comment]
> Fixed

Thanks, can you update the binaries as well?

**Comment by Mivik** [comment]
> Thanks, can you update the binaries as well?

I'm not publishing it as a release but anyway you can get it here: https://gofile.io/d/xqex9k
