### ISSUE TITLE
半自动打歌bug？

### ISSUE THREAD

**Issue by happymimimix** [Mivik/prpr#8]
![image](https://user-images.githubusercontent.com/107282563/219932945-60ea3f07-bf78-4a16-86ce-ae8e58b27dc2.png)
黄健和粉键全自动点击，我没按键盘，没按鼠标，也没开autoplay，这是怎么回事？

**Comment by F-Unction** [comment]
不是你键盘故障？

**Comment by happymimimix** [comment]
确实不是，用lchzh的模拟器就没这bug。

**Comment by happymimimix** [comment]
但是他的模拟器不支持rpe

**Comment by Mivik** [comment]
Fixed by 7f5ebf8599323678f2de230acd3104ba7bcb0aba

**Comment by lchzh3473** [comment]
> 但是他的模拟器不支持rpe

该评论为虚假信息。
https://github.com/lchzh3473/sim-phi/blob/0d08d260d7fb66590cd888f1a46f708bf96ba454/README.md?plain=1#L52

**Comment by happymimimix** [comment]
> > 但是他的模拟器不支持rpe
> 
> 该评论为虚假信息。 https://github.com/lchzh3473/sim-phi/blob/0d08d260d7fb66590cd888f1a46f708bf96ba454/README.md?plain=1#L52

转换RPE谱面到PE格式而已，本质还是不支持。只不过是加了个转换器罢了。
父线能正常使用吗？
贝塞尔曲线支持吗？
文字绘图事件能用吗？
故事板都适配了吗？
大小键能调了吗？
音符可视时间支持吗？

如果你坚决认定能读取RPE的谱面格式就算是适配了那我也没什么好说的。
还有，请你注意下消息发送的时间，在我发那个消息之前你的模拟器是什么样？
连大小键都还没有呢！

**Comment by happymimimix** [comment]
> > 但是他的模拟器不支持rpe
> 
> 该评论为虚假信息。 https://github.com/lchzh3473/sim-phi/blob/0d08d260d7fb66590cd888f1a46f708bf96ba454/README.md?plain=1#L52

我一分钟前刚测的，你最新版的模拟器：
![image](https://github.com/Mivik/prpr/assets/107282563/60a51052-b923-4cf0-b7c8-9eedac1281e3)
大小键没有，音符透明度没有。

**Comment by F-Unction** [comment]
差不多得了，要吵自己发邮件，别在prpr的issue区吵吵

**Comment by happymimimix** [comment]
> > 但是他的模拟器不支持rpe
> 
> 该评论为虚假信息。 https://github.com/lchzh3473/sim-phi/blob/0d08d260d7fb66590cd888f1a46f708bf96ba454/README.md?plain=1#L52

就这你就觉得算是支持RPE了？

**Comment by lchzh3473** [comment]
> > > 但是他的模拟器不支持rpe
> > 
> > 
> > 该评论为虚假信息。 https://github.com/lchzh3473/sim-phi/blob/0d08d260d7fb66590cd888f1a46f708bf96ba454/README.md?plain=1#L52
> 
> 就这你就觉得算是支持RPE了？

如果你认为日期有问题，那么我再贴一个历史commit字段：
https://github.com/lchzh3473/sim-phi/blob/e90f5c62733ff9d2090cf961a3cefe042601bb1a/README.md?plain=1#L47
我支持的rpe并未加上“最新版”字段，请不要望文生义；
如果你坚决认定能读取rpe的谱面格式就意味着适配了最新版rpe，那我无话可说。
本次回复是基于你的评论可能造成的误解，导致多数人认为我的模拟器不支持pez导入；
另外，我已经在文档明确说明，独有特性可能不受支持；但导出的pez谱面并非rpe内部“导出旧pec”功能；
 *已确认该功能会丢失父线事件，造成不支持的误解，因此我会在后续更新的文档标记其为“不推荐使用的功能”。
